---
version: "2.6b3"
name: Simple Scheduler (BETA)
description: Simple timer on weekly base
slug: simplescheduler
url: https://github.com/arthurdent75/SimpleScheduler-BETA
codenotary: notary@home-assistant.io
arch:
  - aarch64
  - amd64
  - armv7
init: false
homeassistant_api: true
ingress: true
panel_title: Scheduler
panel_icon: mdi:calendar-clock
map:
  - share:rw
