name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_FROM: ghcr.io/hassio-addons/debian-base/armhf:5.3.1 
       
jobs:
   docker:
     runs-on: ubuntu-latest

     steps:
        - name: Checkout repository
          uses: actions/checkout@v3
        - name: Extract metadata (tags, labels) for Docker
          id: meta
          uses: docker/metadata-action@v5
          with:
            images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}         
        - name: Set up QEMU
           uses: docker/setup-qemu-action@v3
        - name: Set up Docker Buildx
           uses: docker/setup-buildx-action@v3  
        - name: Build and push by digest
           id: build
           uses: docker/build-push-action@v5
           with:
             context: .
             platforms: ${{ matrix.platform }}
             labels: ${{ steps.meta.outputs.labels }}
             tags: ${{ steps.meta.outputs.tags }}
             outputs: type=image,name=${{ env.REGISTRY_IMAGE }},push-by-digest=true,name-canonical=true,push=true

#             BUILD_FROM=ghcr.io/hassio-addons/debian-base/armhf:5.3.1   
           

