name: Build Docker Multiarch Image

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: arthurdent75/simplescheduler-beta
  
jobs:
  build:
    runs-on: ubuntu-latest
          
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build and push Docker images
        run: |
           version=$(yq e '.version' config.yaml)
           docker buildx build --platform linux/amd64,linux/arm64,arm/v7 -t ghcr.io/arthurdent75/simplescheduler-beta/ --push 
